name: Run Tests
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - packages/**
  push:
    paths:
      - packages/**
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: 18
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: pnpm i

      - name: Run tests
        run: pnpm test
